### ISSUE TITLE
Pictures are not Rendering

### ISSUE THREAD

**Issue by Dmvinedata** [learn-co-curriculum/dsc-the-gradient-in-gradient-descent#1]
## Link to Canvas

https://learning.flatironschool.com/courses/4965/pages/the-gradient-in-gradient-descent?module_item_id=394709

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ X] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
The pictures that go with the Gradient Descent explanations are note rendering.  This lesson in particular, references them to learn.
```

## What OS Are You Using?

- [X ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

I am using a Brave Browser

**Comment by jessepisel** [comment]
thanks for opening this issue :wave: I have updated the image paths in Canvas and it is correct at this time.
